// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-wl37L7I7jSEn18MQFW7cLeMZ6T70zA',
    appId: '1:694892522992:web:49f3d267550e6d114c8135',
    messagingSenderId: '694892522992',
    projectId: 'realestatelisting-8ae36',
    authDomain: 'realestatelisting-8ae36.firebaseapp.com',
    storageBucket: 'realestatelisting-8ae36.firebasestorage.app',
    measurementId: 'G-1P5K1Q4NH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAagexDrtykC3ZEmPatAYCMDIiFFxKNTbc',
    appId: '1:694892522992:android:b2f5f2dd94ae73ec4c8135',
    messagingSenderId: '694892522992',
    projectId: 'realestatelisting-8ae36',
    storageBucket: 'realestatelisting-8ae36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0y2UFy08wQaisj406VPX_lkqKiEuHHLM',
    appId: '1:694892522992:ios:52ee9a2cb03833564c8135',
    messagingSenderId: '694892522992',
    projectId: 'realestatelisting-8ae36',
    storageBucket: 'realestatelisting-8ae36.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0y2UFy08wQaisj406VPX_lkqKiEuHHLM',
    appId: '1:694892522992:ios:52ee9a2cb03833564c8135',
    messagingSenderId: '694892522992',
    projectId: 'realestatelisting-8ae36',
    storageBucket: 'realestatelisting-8ae36.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn-wl37L7I7jSEn18MQFW7cLeMZ6T70zA',
    appId: '1:694892522992:web:6cd95eb53f2ca0a24c8135',
    messagingSenderId: '694892522992',
    projectId: 'realestatelisting-8ae36',
    authDomain: 'realestatelisting-8ae36.firebaseapp.com',
    storageBucket: 'realestatelisting-8ae36.firebasestorage.app',
    measurementId: 'G-ERR0C12BZR',
  );
}
